### ISSUE TITLE
GSEA html reports have broken links to png and TSV files

### ISSUE THREAD

**Issue by vmkalbskopf** [nf-core/differentialabundance#260]
### Description of the bug

None of the GSEA generated html reports render png images. The html source indicates that the images should be in the same directory has the html files. But the images are placed elsewhere. The same is true for the TSV files linked in the reports.

### Relevant files

[example_broken_html_files.zip](https://github.com/nf-core/differentialabundance/files/14929324/example_broken_html_files.zip)

### System information

Tested on current dev version
```
GSEA_GSEA:
  gsea: 4.3.2
TABULAR_TO_GSEA_CHIP:
  bash: 4.2.25 3
Workflow:
    nf-core/differentialabundance: v1.5.0
    Nextflow: 23.10.1
```
