### ISSUE TITLE
Switch to formula-based model definition

### ISSUE THREAD

**Issue by grst** [nf-core/differentialabundance#429]
### Description of feature

Just switch to formula-based model defintion. Don't support any more complex models (yet). 

I.e. instead of 
```yaml
contrasts:
  - id: condition_control_treated_blockrep
    comparison: ["condition", "control", "treated"]
    blocking_factors: ["replicate"]
```

use
```yaml
contrasts:
  -  id: condition_control_treated_blockrep
     formula: ~ condition + replicate
     comparison: ["condition", "control", "treated"]
```

Sub issue of #362
