### ISSUE TITLE
Redundant parameters still required with `formula` and `contrast`

### ISSUE THREAD

**Issue by atrigila** [nf-core/differentialabundance#451]
Currently, even when specifying `formula` and `makeContrasts`, the `comparison` parameter is still required due to constraints in `validatefomcomponents`. This is because the module `VALIDATOR` produces a TSV with `comparison` and related columns.

This behavior should be reviewed and potentially refactored to avoid redundancy. If the input is a yaml file, then we could investigate if `comparison` can be safely deprecated or removed when `formula` and `contrast` are defined.

**Comment by atrigila** [comment]
One aspect that could be improved is the use of `oneOf` in the JSON schema validation, allowing only one of `comparison` or `make_contrast_str`. 

It should be noted that we would still require to modify `validatefomcomponents` as the variable/target/reference are still required.

**Comment by atrigila** [comment]
Example contrasts YAML file that should be valid with changes to `validatefomcomponents`:
```
contrasts:
  - id: treatment_mCherry_hND6_
    comparison: ["treatment", "Control", "Treated"]

  - id: treatment_mCherry_hND6_batch
    comparison: ["treatment", "Control", "Treated"]
    blocking_factors: ["batch"]

  - id: treatment_effect
    formula: "~ treatment"
    comparison: ["treatment", "Control", "Treated"]

  - id: treatment_plus_genotype
    formula: "~ treatment + genotype"
    make_contrasts_str: "treatmentTreated"

  - id: interaction_genotype_treatment
    formula: "~ genotype * treatment"
    make_contrasts_str: "genotypeWT.treatmentTreated"

  - id: full_model_with_interactions
    formula: "~ genotype * treatment * time"
    make_contrasts_str: "genotypeWT.treatmentTreated.time"
```

**Comment by grst** [comment]
It's debatable if we want to support the combination of `formula` + `comparison`. I think I once argued *for* it, but it could be non-trivial to translate a comparison-tuple into a contrast because it depends on how the formula looks like and what the base categories of a column are. 

So it would be fine for me to support only `comparison` + `blocking_factors` or `formula` + `make_contrasts_str` if that makes things easier.

**Comment by atrigila** [comment]
Yes, I agree and that was my initial thought. Either:  
- `comparison` + `blocking_factors`  OR
- `formula` + `make_contrasts_str`

I have been working on a PR to shinyngs that was able to handle this combinations. I'll share it shortly.

**Comment by atrigila** [comment]
For my reference / testing pursposes, these will be invalid combinations:
```
contrasts:
  - id: treatment_effect
    formula: "~ treatment"
    comparison: ["treatment", "Control", "Treated"]
  - id: interactions_and_blocking
    formula: "~ genotype * time"
    make_contrasts_str: "genotypeWT.treatmentTreated.time"
    blocking_factors: ["batch", "treatment"]
```
