### ISSUE TITLE
Allow specification of ANOVA-like contrasts

### ISSUE THREAD

**Issue by grst** [nf-core/differentialabundance#455]
### Description of feature

linear models allow to test for any of multiple variables being different, equivalent to the classical ANOVA. 

In limma, this is possible by specifying a list of multiple coefficients to `topTable`. In DESeq2, this is possible by specifying a full and reduced model to perform a likelihood ratio test. 

We should find a way of enabling this across methods, ideally using a consistent way of specifying ANOVA-like contrasts, e.g. 

```yaml
contrasts:
 - id: check_treatment_effect
   type: full_vs_reduced
   full: "~treatment + response"
   reduced: "~ response"
```

First thing is to evaluate for all implemented methods, if and how they support the ANOVA case.
