### ISSUE TITLE
Update docs on contrast specification

### ISSUE THREAD

**Issue by grst** [nf-core/differentialabundance#461]
### Description of feature

The `dev` docs still show `formula` together with a comparison tuple. Instead, a "contrast str" should be provided. 

```yaml
  - id: condition_control_treated_blockrep
    formula: "~ condition + replicate"
    comparison: ["condition", "control", "treated"]
```

https://nf-co.re/differentialabundance/dev/docs/usage/#yaml-contrasts-file-format

Please update the documentation such that it reflects how this is currently implemented in DREAM, and will be implemented in limma (#458) and DESeq2 (#459). Please also add a description how these contrasts strings can be derived.
